### ISSUE TITLE
Understanding the fragmented nature of the code

### ISSUE THREAD

**Issue by davecranwell** [tayiorbeii/reactify-cards#2]
This repo seems to exist for teaching purposes, so I was hoping you might care to help a React newbie. One thing I've struggled to grasp is a consistent rationale for _when_ you create a whole component, instead of just using regular HTML and a tiny bit of JS in the container component.

Take the functional component `CardHeader` for example. It amounts to little more than a ternary operator, rendering a single, undecorated `div`. 

Whats the reason for not having `headerComponent` get calculated in the `Card` component, then output directly into the `Card` `render()` call? Testability? More FP-style code? Interested to know.

**Comment by tayiorbeii** [comment]
@davecranwell Good timing, I just finished the first draft of the whole writeup yesterday, and happen to be online right now! I'm not sure if you've read the whole thing, but here are some thoughts...

As far as the `CardHeader` goes, sure, it's entirely possible to calculate the header inside of `Card` (and as seen in the `StaticCards` markup you can just have a bunch of markup be a component). The problem is that it becomes less composable (and potentially less readable) with that approach.

If we were creating a Lego figure, there are several parts that can pull apart:
* `Head`
* `LeftArm` (which contains a`Hand` component)
* `RightArm` (containing another instance of the same `Hand` component)
* `Body` (which includes `RightArm` and `LeftArm`)
* `Leg` (I'm pretty sure Lego figures have two of the same leg?)

If you wanted to paint the `RightArm`, In my opinion it would be easier to do so if nothing was attached to it than trying to work a fine tipped paintbrush around the `UpperBody` as a whole.

I hope that helps!

I really do suggest doing the exercise in [the section on component planning](https://github.com/tayiorbeii/reactify-cards/tree/03-component-planning) for your design. I think it will help you with your own design. Feel free to upload any screenshots here and I'll take a look!

**Comment by davecranwell** [comment]
Nice answer, thanks. I suppose the `CardHeader` _does_ have a small amount of logic unique to the requirements of the header, so keeping it as a component has a value in terms of separation of responsibilities. I would probably extract it out in a later optimisation pass, rather than straight away, but I expect this is something _you_ do having had the experience to know up front that you'll almost certainly want to do it. Thanks again :)

**Comment by tayiorbeii** [comment]
@davecranwell Cool, glad that helped!
